### ISSUE TITLE
gUM intercept

### ISSUE THREAD

**Issue by ggarber** [ggarber/webrtc-intercept#7]
Ok, now I need to intercept gUM (to capture from a canvas).    New repo "gum-intercept" or multiple sections in this README ?

@fippo @juandebravo I will obey your orders

**Comment by fippo** [comment]
maybe just have the js code as .js files?

**Comment by ggarber** [comment]
Will add the .js but I still want to put examples / use-cases in the README.   I will try to keep all together in a single README.

What do you think of this initial implementation?

```js
<script>
(function() {
  function wrap(gUM) {
    return function() {
      return gUM.apply(this, arguments);
    };
  }

  if (navigator.mediaDevices.getUserMedia) {
    navigator.mediaDevices.getUserMedia = wrap(navigator.mediaDevices.getUserMedia); 
  }
  ['getUserMedia', 'webkitGetUserMedia', 'mozGetUserMedia'].forEach(function(name) {
    navigator[name] = wrap(navigator[name]);
  });
})();
```

**Comment by juandebravo** [comment]
LGTM

**Comment by fippo** [comment]
you did obey. Resistance is futile!
